### ISSUE TITLE
Upgrade typescript source code to the latest

### ISSUE THREAD

**Issue by gfx** [typescript-ruby/typescript-src-ruby#5]
The layout of source files of 1.4.x is too different from 1.0.0.

**Comment by bdrazhzhov** [comment]
I think it would be great to use installed typescript compiler if it is installed. But if compiler would not be found in system gem would use internal compiler.

**Comment by bdrazhzhov** [comment]
Typescript source code is updated to v1.4.1.

**Comment by amritk** [comment]
@bdrazhzhov could you update on [rubygems?](https://rubygems.org/gems/typescript-src)

**Comment by bdrazhzhov** [comment]
Currently I don't have permission for updating on rubygems. I've asked owner about it. When I get permission I'll update gem on rubygems.

**Comment by bdrazhzhov** [comment]
@amritk, I've pushed new version of gem to rubygems.
